name: Deploy Vue App to GitHub Pages

on:
  push:
    branches:
      - main  # 或者是你用於開發的分支，比如 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.6.0' # 根據正在使用嘅 node 版本

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: main 
        FOLDER: dist  # Vue CLI 建立的生產構建目錄
        CLEAN: true  # 清除舊文件
